# Generated by Django 2.2.6 on 2020-06-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pass_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
