# Generated by Django 2.2.6 on 2020-06-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0002_question_pass_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pass_percent',
            new_name='pass_ratio',
        ),
    ]
