# Generated by Django 2.2.6 on 2020-06-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0007_auto_20200617_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
