# Generated by Django 2.2.6 on 2020-06-18 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='no',
        ),
        migrations.RemoveField(
            model_name='status',
            name='subject',
        ),
        migrations.AddField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='luogu.Question'),
        ),
    ]
