# Generated by Django 2.2.6 on 2020-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0002_auto_20200618_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='date',
        ),
        migrations.RemoveField(
            model_name='status',
            name='question',
        ),
        migrations.AddField(
            model_name='status',
            name='no',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='subject',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='luogu.Question')),
            ],
            options={
                'db_table': 'History',
            },
        ),
    ]
