# Generated by Django 2.2.6 on 2020-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0003_auto_20200618_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
