# Generated by Django 2.2.6 on 2020-06-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luogu', '0004_question_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'get_latest_by': 'date'},
        ),
    ]
