# Generated by Django 2.2.6 on 2020-06-21 14:22

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
